name: 自动申请证书

on: push

jobs:
  job1:
    name: 自动化申请证书
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: 获取仓库内容
        uses: actions/checkout@v4
      - name: 创建 Python 虚拟环境并安装依赖
        shell: bash
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt
      - name: 正式申请证书
        shell: bash
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          SMTP_RECIPIENTS: ${{ secrets.SMTP_RECIPIENTS }}
          SMTP_SENDER_EMAIL: ${{ secrets.SMTP_SENDER_EMAIL }}
          SMTP_SENDER_PASSWORD: ${{ secrets.SMTP_SENDER_PASSWORD }}
        run: | 
          source ./venv/bin/activate
          python main.py
